# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: dclark <dclark@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/02/04 11:23:37 by dclark            #+#    #+#              #
#    Updated: 2021/02/19 13:31:20 by dclark           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME	= cub3D
all:	
	gcc -fsanitize=address -I ./ $(SRC) libft.a libmlx.a -lmlx -framework OpenGL -framework AppKit -o $(NAME)
